### ISSUE TITLE
Python Module

### ISSUE THREAD

**Issue by Blender3D** [petewarden/geodict#3]
Could you add a blank `__init__.py` file into your folder? I'm importing `geodict` as a module and have to create the file manually.

Thanks for the awesome script!

**Comment by petewarden** [comment]
I've just checked a blank file called **init**.py into the python folder, does that do the trick for you?

cheers,
           Pete

**Comment by Blender3D** [comment]
Yep, that does it. Thanks!

**Comment by Blender3D** [comment]
Do you mean `__init__.py` or `init.py`?

**Comment by petewarden** [comment]
`__init__.py`, sorry the markdown swallowed the double underscores in the first comment.

**Comment by Blender3D** [comment]
Sorry about that then. Thanks!
